networks:
  dev:
    driver: bridge

services:
  web:
    container_name: frontend-vue
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - dev
    volumes:
      - "./.nginx/nginx.conf:/etc/nginx/nginx.conf"
#      - "./.nginx/certbot/conf:/etc/letsencrypt"
#      - "./.nginx/certbot/www:/var/www/certbot"

